# Домашнее задание №5

### Задание №1 (1,5 балла)

Создайте два массива: в первом должны быть четные числа от 2 до 12 включительно, а в другом числа 7, 11, 15, 18, 23, 29.

$1.$ Сложите массивы и возведите элементы получившегося массива в квадрат:

In [12]:
import numpy as np
a = np.array([2, 4, 6, 8, 10, 12])
b = np.array([7, 11, 15, 18, 23, 29])
c = a + b
c = c * c
print(c)

[  81  225  441  676 1089 1681]


$2.$ Выведите все элементы из первого массива, которые стоят на тех местах, где элементы второго массива больше 12 и дают остаток 3 при делении на 5.

In [15]:
ind_b = np.logical_and(b>12, b%5==3)
print(ind_b)
print(a[3])
print(a[4])

[False False False  True  True False]
8
10


*3.* Для первого массива найдите остатки от деления на 2, а для второго --- на 3. Для каждого получившегося массива выведите его уникальные значения (см. семинар).

In [17]:
m = a%2
n = b%3
print(m)
print(n)

[0 0 0 0 0 0]
[1 2 0 0 2 2]


### Задание №2 (1,5 балла)

Найдите интересный для вас датасет. Например, можно выбрать датасет [тут](http://data.un.org/Explorer.aspx) или [тут](https://hls.harvard.edu/library/research/find-a-database/). Если выскакивают ошибки при считывании таблицы, попробуйте их погуглить и решить проблему!

1. Рассчитайте подходящие описательные статистики для признаков объектов в выбранном датасете
2. Проанализируйте и прокомментируйте содержательно получившиеся результаты
    - недостаточно написать фразы формата "Средний возраст = 60, а минимальный = 20", следует дать пояснение, что это значит и какие выводы можно сделать в рамках датасета
3. Все комментарии оформляйте строго в ячейках формата Markdown
    - для этого надо в выпадающем окошке сверху для текущей ячейки сменить тип Code на Markdown
    ![](https://i.imgur.com/vl7Fmg9.png)

In [ ]:
# YOUR CODE